spring.application.name=event-catalog-service

spring.datasource.url=jdbc:postgresql://localhost:5433/eventforge_catalog
spring.datasource.username=eventforge
spring.datasource.password=eventforge

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info
